In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [8]:
x = np.full((3,3),1)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## Q#2: Create y array with elements equal to 0.

In [9]:
y = np.zeros((3,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q#3: Add x and y arrays.

In [10]:
np.add(x,y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [12]:
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)

(3, 3)
2
9
int32


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [17]:
w = np.array([[11,12],[13,14],[15,16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [25]:
z= np.array([[1],[2],[3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [27]:
newArray = np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [28]:
for i in newArray:
    for j in i:
        print(j)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [29]:
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [42]:
newArray = np.add(newArray,np.full((3,3),-1))



## Q#11: Find smallest and biggest values in "newArray".

In [43]:
newArray.min()

0

## Q#12: Print the first row of "newArray" using indexing.

In [44]:
newArray.max()

15

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [54]:
np.where(12 == newArray)

(array([1], dtype=int64), array([1], dtype=int64))

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [57]:
print(np.where(0 == newArray ))
print(np.where(13 == newArray))

(array([0], dtype=int64), array([0], dtype=int64))
(array([1], dtype=int64), array([2], dtype=int64))


## Q#15: Change the shape of "newArray" to (9,1).

In [58]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [59]:
newArray.reshape(3,3)

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

# Well Done 🎉