In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [12]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [10]:
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [15]:
result = np.add(x,y)
result

array([1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [22]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)


1
(5,)
5
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [30]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [28]:
z = np.array([1,2,3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [66]:
newArray = np.hstack((z.reshape(3,1),w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [58]:
for index in newArray:
    print(index)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9:Reverse  the columns and rows of "newArray".

In [59]:
r = np.flip(newArray)
r

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [67]:
newArray = newArray-1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [71]:
print(np.min(newArray))
print(np.max(newArray))

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [72]:
newArray[0]

array([ 0, 10, 11])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [75]:
print(newArray)
newArray[1,1]

[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [80]:
print(newArray)
print(newArray[0,0])
print(newArray[1,2])


[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]
0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [81]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [84]:
newArray.reshape(3,3)

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

# Well Done 🎉