In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [57]:
x = np.ones((2,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


## Q#2: Create y array with elements equal to 0.

In [58]:
y = np.zeros((2,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


## Q#3: Add x and y arrays.

In [59]:
print(np.add(x,y))

[[1. 1. 1.]
 [1. 1. 1.]]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [60]:
print('dimension: ', x.ndim)
print('shape: ', x.shape)
print('size: ', x.size)
print('typ: ', x.dtype)
print('item size: ', x.itemsize)
print('data: ', x.data)

dimension:  2
shape:  (2, 3)
size:  6
typ:  float64
item size:  8
data:  <memory at 0x000001D9A37BB5E0>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [61]:
w = np.array([(11, 12), (13, 14), (15,16)])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [62]:
z = np.array([1, 2, 3])
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [78]:
z = z.reshape(3, 1)
newArray = np.hstack((z, w))

print(newArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [66]:
for row in newArray:
    for element in row:
        print(element, end=" ")
    print()

1 11 12 
2 13 14 
3 15 16 


## Q#9: Reverse the columns and rows of "newArray".

In [68]:
newArray = np.transpose(newArray)
print(newArray)

[[ 1  2  3]
 [11 13 15]
 [12 14 16]]


## Q#10: Decrement all elements of "newArray" with 1.

In [69]:
newArray -= 1
print(newArray)

[[ 0  1  2]
 [10 12 14]
 [11 13 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [70]:
min_value = np.min(newArray)
max_value = np.max(newArray)

print("Min value:", min_value)
print("Max value:", max_value)

Min value: 0
Max value: 15


## Q#12: Print the first row of "newArray" using indexing.

In [71]:
print(newArray[0])

[0 1 2]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [72]:
print(newArray[1, 1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [75]:
print(newArray[0, 0])
print(newArray[2, 1])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [76]:
newArray = newArray.reshape(9, 1)
print(newArray)

[[ 0]
 [ 1]
 [ 2]
 [10]
 [12]
 [14]
 [11]
 [13]
 [15]]


## Q#16: Change the shape of "newArray" to (3,2).

In [79]:
# cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉