In [322]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [323]:
x = np.ones([3,3])
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [324]:
y = np.zeros([3,3])
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [325]:
np.add(x,y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [326]:
print(x.shape)
print(x.size)
print(x.ndim)
print(x.ndim)

(3, 3)
9
2
2


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [327]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [328]:
z = np.array([1,2,3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [329]:
newArray = np.append(z,w)
print(newArray)

[ 1  2  3 11 12 13 14 15 16]


In [330]:
newArray.shape = (3,3)
newArray

array([[ 1,  2,  3],
       [11, 12, 13],
       [14, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [331]:
for i in newArray:
    for j in i:
        print(j)

1
2
3
11
12
13
14
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [332]:
newArray.transpose()

array([[ 1, 11, 14],
       [ 2, 12, 15],
       [ 3, 13, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [333]:
newArray = np.subtract(newArray,1)
newArray

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [334]:
print(newArray.min())
print(newArray.max())

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [335]:
newArray[0:1]

array([[0, 1, 2]])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [336]:
print(np.where(newArray == 12))
print(newArray[1:2])

(array([1]), array([2]))
[[10 11 12]]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [347]:
print(np.where(newArray == [0]))
print(np.where(newArray == [13]))



(array([0]), array([0]))
(array([2]), array([0]))


## Q#15: Change the shape of "newArray" to (9,1).

In [353]:
newArray.reshape(9,1)

array([[ 0],
       [ 1],
       [ 2],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [355]:
newArray.reshape(3,3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

# Well Done 🎉