In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
x = np.ones(1)
x

array([1.])

## Q#2: Create y array with elements equal to 0.

In [3]:

y = np.zeros(1)
y

array([0.])

## Q#3: Add x and y arrays.

In [4]:

np.add(x,y)

array([1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)

(1,)
1
1
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [6]:

w = np.array([[11, 12], [13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [7]:

z = np.arange(start=1, stop=4, step=1)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [8]:

NewW = np.hstack(w)
newArray = np.hstack((z,NewW))
newArray

array([ 1,  2,  3, 11, 12, 13, 14, 15, 16])

## Q#8: Print all elements of "newArray" using the loop.

In [9]:
for i in newArray:
 print(i)

1
2
3
11
12
13
14
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [10]:

newArray=newArray.reshape(3,1,3)
print(newArray)
newArray.transpose()

[[[ 1  2  3]]

 [[11 12 13]]

 [[14 15 16]]]


array([[[ 1, 11, 14]],

       [[ 2, 12, 15]],

       [[ 3, 13, 16]]])

## Q#10: Decrement all elements of "newArray" with 1.

In [11]:

ones= np.ones((3,1,3))
newArray=np.subtract(newArray, ones)
newArray

array([[[ 0.,  1.,  2.]],

       [[10., 11., 12.]],

       [[13., 14., 15.]]])

## Q#11: Find smallest and biggest values in "newArray".

In [12]:
newArray.min()

0.0

## Q#12: Print the first row of "newArray" using indexing.

In [13]:
print(newArray[1])

[[10. 11. 12.]]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [14]:
element = newArray[1, 0, 2]
print(element)

12.0


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [15]:
element = newArray[2, 0, 0]
print(element)

13.0


## Q#15: Change the shape of "newArray" to (9,1).

In [16]:
newArray.reshape(9,1)

array([[ 0.],
       [ 1.],
       [ 2.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.]])

## Q#16: Change the shape of "newArray" to (3,2).

In [17]:
idx = [8 , 7, 6]
newNewArray = np.delete(newArray, idx)
newNewArray.reshape(3,2)

array([[ 0.,  1.],
       [ 2., 10.],
       [11., 12.]])

# Well Done 🎉