In [52]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [53]:
# write your code here ^_^
x = np.ones(4)
x

array([1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [54]:
# write your code here ^_^
y = np.zeros(4)
y

array([0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [55]:
# write your code here ^_^
result = x + y
result


array([1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [56]:
# write your code here ^_^
print("x array characteristics:")
print(f"Dimension: {x.ndim}")
print(f"Shape: {x.shape}")
print(f"Size: {x.size}")
print(f"Type: {x.dtype}")

x array characteristics:
Dimension: 1
Shape: (4,)
Size: 4
Type: float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [57]:
# write your code here ^_^
w = np.array([[11, 12], [13, 14], [15, 16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [58]:
# write your code here ^_^
z = np.array([1, 2, 3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [59]:
# write your code here ^_^
newArray = np.hstack((z[:, np.newaxis], w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [60]:
# write your code here ^_^
print("Elements of newArray:")
for row in newArray:
    for element in row:
        print(element, end=" ")
    print()

Elements of newArray:
1 11 12 
2 13 14 
3 15 16 


## Q#9: Reverse the columns and rows of "newArray".

In [61]:
# write your code here ^_^
newArray = newArray[::-1, ::-1]
newArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [62]:
# write your code here ^_^
def f(x):
  return x-1
newArray=f(newArray)
newArray

array([[15, 14,  2],
       [13, 12,  1],
       [11, 10,  0]])

## Q#11: Find smallest and biggest values in "newArray".

In [63]:
# write your code here ^_^
smallest = np.min(newArray)
biggest = np.max(newArray)
print(f"Smallest value: {smallest}")
print(f"Biggest value: {biggest}")

Smallest value: 0
Biggest value: 15


## Q#12: Print the first row of "newArray" using indexing.

In [64]:
# write your code here ^_^
first_row = newArray[0, :]
print("First row of newArray:", first_row)

First row of newArray: [15 14  2]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [65]:
# write your code here ^_^
num_12 = newArray[newArray == 12]
print("Number equal to 12 in newArray:", num_12)


Number equal to 12 in newArray: [12]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [66]:
# write your code here ^_^
num_0_13 = newArray[(newArray == 0) | (newArray == 13)]
print("Numbers equal to 0 and 13 in newArray:", num_0_13)

Numbers equal to 0 and 13 in newArray: [13  0]


## Q#15: Change the shape of "newArray" to (9,1).

In [67]:
# write your code here ^_^
newArray = newArray.reshape((9, 1))
newArray

array([[15],
       [14],
       [ 2],
       [13],
       [12],
       [ 1],
       [11],
       [10],
       [ 0]])

## Q#16: Change the shape of "newArray" to (3,3).

In [68]:
# write your code here ^_^
newArray = newArray.reshape((3, 3))
newArray

array([[15, 14,  2],
       [13, 12,  1],
       [11, 10,  0]])

# Well Done 🎉