In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [4]:
#Q1
x=np.array(1)

## Q#2: Create y array with elements equal to 0.

In [6]:
#Q2
y=np.array(0)

## Q#3: Add x and y arrays.

In [7]:
#Q3
xy=np.add(x,y)
print(xy)

1


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [8]:
#Q4
print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  int32
number of dimensions =  0
shape =  ()
size =  1


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [3]:
#Q5
w=np.array([11,12,13,14,15,16])
w=np.reshape(w,(3,2))
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [9]:
#Q6
z=np.arange(1,3+1)
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [10]:
#Q7
z=z.reshape(3,1)
newArray=np.hstack((w,z))
print(newArray)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [11]:
#Q8
for i in newArray:
    for j in i:
        print(j)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [12]:
#Q9
newArray=newArray.transpose()
print(newArray)

[[11 13 15]
 [12 14 16]
 [ 1  2  3]]


## Q#10: Decrement all elements of "newArray" with 1.

In [13]:
#Q10
newArray=np.subtract(newArray,1)
print(newArray)

[[10 12 14]
 [11 13 15]
 [ 0  1  2]]


## Q#11: Find smallest and biggest values in "newArray".

In [14]:
#Q11
print("Smallest element:",newArray.min(),sep=' ')
print("Bigest element:",newArray.max(),sep=' ')

Smallest element: 0
Bigest element: 15


## Q#12: Print the first row of "newArray" using indexing.

In [15]:
#Q12
print(newArray[0])

[10 12 14]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [16]:
#Q13
print(newArray[newArray == 12])

[12]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [17]:
#Q14
print(newArray[newArray == 13],newArray[newArray ==0])

[13] [0]


## Q#15: Change the shape of "newArray" to (9,1).

In [18]:
#Q15
newArray=newArray.reshape(9,1)
print(newArray)

[[10]
 [12]
 [14]
 [11]
 [13]
 [15]
 [ 0]
 [ 1]
 [ 2]]


## Q#16: Change the shape of "newArray" to (3,2).

In [19]:
#Q16
newArray=newArray.reshape(3,3)
print(newArray)

[[10 12 14]
 [11 13 15]
 [ 0  1  2]]


# Well Done 🎉